### PR TITLE
ENTESB-9274 Missing me.snowdrop:narayana-spring-boot-starter in BOM

### PR DESCRIPTION
**Pull request by cunningt**
https://issues.jboss.org/browse/ENTESB-9274

### CODE REVIEW

**Comment by cunningt** [comment]
These changes need accompanying changes from fabric8 here 

https://github.com/jboss-fuse/fabric8/pull/1156

**Comment by cunningt** [comment]
@nicolaferraro Added the postgresql dependency.    We can depend on the redhat-fuse BOM for the version of postgresql to bring in, that's being brought in by the includes on spring-boot-dependencies -> fabric8-camel-spring-boot -> redhat-fuse.

**Comment by cunningt** [comment]
@nicolaferraro I added it the postgres dependency back to the PR.     I've been stalled by build failures in fabric8 and in fuse-components from getting out a 7.2 build.

Does this look okay now with the inclusion of the postgres dep?

**Comment by nicolaferraro** [comment]
@cunningt from a project point of view I see no issues, but you've removed the version information from the postgresql dependency and I don't see postgresql in the fuse spring-boot BOM.

That's why I think the build would fail if we merge this.

**Comment by cunningt** [comment]
@nicolaferraro I've removed the version information from the postgresql dependency because it will be pulled into the redhat-fuse BOM through the fabric8 camel-spring-boot BOM, which is what James was saying here : https://github.com/jboss-fuse/redhat-fuse/pull/16

fabric8 is pulling in postgresql version from spring-boot-dependencies: https://github.com/jboss-fuse/fabric8/blob/3.0.11.redhat-7.x/pom.xml#L1324

It's sort of confusing following the parent trail here, but I tested it with SNAPSHOTs locally and it worked.

**Comment by nicolaferraro** [comment]
Ok!

**Pull request merged**
